/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_murilo_java_NativeCodeSample */

#ifndef _Included_com_murilo_java_NativeCodeSample
#define _Included_com_murilo_java_NativeCodeSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_murilo_java_NativeCodeSample
 * Method:    myNativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_murilo_java_NativeCodeSample_myNativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
